### ISSUE TITLE
종량제 봉투용 쓰레기통

### ISSUE THREAD

**Issue by theand** [theand/stuff-sharing#11]
![share-3](https://cloud.githubusercontent.com/assets/854492/18024668/f4d54eac-6c4a-11e6-8788-7ac835d3eccd.jpg)
![share-4](https://cloud.githubusercontent.com/assets/854492/18024669/f76af680-6c4a-11e6-9eca-ae5c0156453e.jpg)

서울살때 쓰고 제주로 와선 쓰지 않아서 기억이 안나지만

바깥 케이스 안에
봉투를 넣고
뼈대를 잡아주는 내부 틀을 넣고
뚜껑은 사진 위치대로 쓰다가 옆에 홈으로 돌리면 밑으로 쭉 눌러서 압축할 수 있는 쓰레기통이에요.

쓰레기봉투 용량은 기억나지 않네요;;
20L 아니면 40L 일텐데...

아무튼 이거랑 비슷.
http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=1316882075&vkey=RLHIS0HZX24SKUXZ3933LKVUU4XMJ4&utm_term=

**Comment by bams86** [comment]
저요!!!
