### ISSUE TITLE
비닐봉지 보관함

### ISSUE THREAD

**Issue by theand** [theand/stuff-sharing#12]
![share-5](https://cloud.githubusercontent.com/assets/854492/18024687/64450a34-6c4b-11e6-8188-7819d8273b4f.jpg)

각종 비닐봉지
재활용하려고 어디에 쑤셔 박아두기 애매한데
여기에 몰아놓고 뽑아쓰는 용도입니다.

**Comment by bams86** [comment]
저요!!!
