### ISSUE TITLE
조립식수납함?

### ISSUE THREAD

**Issue by theand** [theand/stuff-sharing#5]
![conserv1](https://cloud.githubusercontent.com/assets/854492/17959191/b05cde42-6ad9-11e6-9aef-da008db509d4.jpg)
![conserv2](https://cloud.githubusercontent.com/assets/854492/17959190/b05cbbba-6ad9-11e6-9076-088a638f8460.jpg)

조립식이고, 높이는 통돌이 세탁기랑 비슷.
뒤쪽으로 깊이는 40cm 쯤 되보여요.

**Comment by theand** [comment]
잡동사니 넣어놓는 보관함으로 썼고, 신발장 등으로도 사용 가능하고요.

**Comment by wukday** [comment]
1빠!

**Comment by bams86** [comment]
먼저 도착하는 사람이 임자
