### ISSUE TITLE
[유료] 빈백

### ISSUE THREAD

**Issue by theand** [theand/stuff-sharing#6]
![beanbag1](https://cloud.githubusercontent.com/assets/854492/17959323/9c7bca04-6ada-11e6-957a-22cd445c84a6.JPG)
![beanbag2](https://cloud.githubusercontent.com/assets/854492/17959322/9c7a1358-6ada-11e6-86b3-d846f8ba6d11.JPG)

제주맘에 3만원에 올려놓은건데 아직 거래가 안되서 혹시나 해서 올려요;
지인할인 2.5만원에 올립니다. ㅋ

http://hugdesign.com/product/detail.html?product_no=30&cate_no=4&display_group=2 
여기 나온 것과 같은 이름의 제품인데, 상품만큼 크지는 않고. 저 사이즈의 2/3 쯤인 것 같은데
제가 구입한 이후로 사이즈가 더 키워져서 업그레이드가 된걸지도 모르겠습니다.

다른 빈백에 사용하고 남은 충전재가 반봉지(?) 남아 있는데 같이 드리겠습니다.

**Comment by bams86** [comment]
저요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by hellodw** [comment]
2빠
